# -*- mode: python ; coding: utf-8 -*-
import os
# Use CWD when run by PyInstaller (no __file__); otherwise use script directory
_spec_dir = os.getcwd()

a = Analysis(
    ['sharepoint_dynamic.py'],
    pathex=[_spec_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        'office365',
        'office365.sharepoint',
        'office365.sharepoint.client_context',
        'office365.runtime.auth',
        'office365.runtime.auth.client_credential',
        'office365.runtime.auth.certificate_credential',
        'dotenv',
        'dotenv.main',
        'dotenv.parser',
        'pandas',
        'openpyxl',
        'fuzzywuzzy',
        'fuzzywuzzy.fuzz',
        'thefuzz',
        'thefuzz.fuzz',
        'Levenshtein',
        'match_excel',
        'logging',
        'json',
        're',
        'datetime',
        'os',
        'itertools',
        'argparse',
        'sys',
        'matrix',
        'sharepoint_audit_logger',
        'matching',
        'matching.orchestrator',
        'matching.data_processing',
        'matching.matching_engine',
        'matching.pass1',
        'matching.pass2',
        'matching.pass3',
        'matching.output_handler',
        'matching.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FRCIStatementRecon',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Changed to True to see console output for debugging
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)