# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['sharepoint.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'office365',
        'office365.sharepoint',
        'office365.sharepoint.client_context',
        'office365.runtime.auth',
        'office365.runtime.auth.client_credential',
        'office365.runtime.auth.certificate_credential',
        'dotenv',
        'pandas',
        'openpyxl',
        'fuzzywuzzy',
        'fuzzywuzzy.fuzz',
        'thefuzz',
        'thefuzz.fuzz',
        'Levenshtein',
        'match_excel',
        'logging',
        'json',
        're',
        'datetime',
        'os',
        'itertools',
        'argparse',
        'sys'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='sharepoint',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Changed to True to see console output for debugging
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)